/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreatePointEventResponseDto
    /// </summary>
    [DataContract(Name = "CreatePointEventResponseDto")]
    public partial class CreatePointEventResponseDto : IEquatable<CreatePointEventResponseDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePointEventResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePointEventResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePointEventResponseDto" /> class.
        /// </summary>
        /// <param name="msg">msg (required).</param>
        /// <param name="_event">_event (required).</param>
        /// <param name="userTotalPoints">userTotalPoints (required).</param>
        public CreatePointEventResponseDto(string msg = default(string), PointEvent _event = default(PointEvent), decimal userTotalPoints = default(decimal))
        {
            // to ensure "msg" is required (not null)
            if (msg == null) {
                throw new ArgumentNullException("msg is a required property for CreatePointEventResponseDto and cannot be null");
            }
            this.Msg = msg;
            // to ensure "_event" is required (not null)
            if (_event == null) {
                throw new ArgumentNullException("_event is a required property for CreatePointEventResponseDto and cannot be null");
            }
            this.Event = _event;
            this.UserTotalPoints = userTotalPoints;
        }

        /// <summary>
        /// Gets or Sets Msg
        /// </summary>
        [DataMember(Name = "msg", IsRequired = true, EmitDefaultValue = false)]
        public string Msg { get; set; }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = false)]
        public PointEvent Event { get; set; }

        /// <summary>
        /// Gets or Sets UserTotalPoints
        /// </summary>
        [DataMember(Name = "userTotalPoints", IsRequired = true, EmitDefaultValue = false)]
        public decimal UserTotalPoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePointEventResponseDto {\n");
            sb.Append("  Msg: ").Append(Msg).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  UserTotalPoints: ").Append(UserTotalPoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreatePointEventResponseDto);
        }

        /// <summary>
        /// Returns true if CreatePointEventResponseDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CreatePointEventResponseDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreatePointEventResponseDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Msg == input.Msg ||
                    (this.Msg != null &&
                    this.Msg.Equals(input.Msg))
                ) && 
                (
                    this.Event == input.Event ||
                    (this.Event != null &&
                    this.Event.Equals(input.Event))
                ) && 
                (
                    this.UserTotalPoints == input.UserTotalPoints ||
                    this.UserTotalPoints.Equals(input.UserTotalPoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Msg != null)
                {
                    hashCode = (hashCode * 59) + this.Msg.GetHashCode();
                }
                if (this.Event != null)
                {
                    hashCode = (hashCode * 59) + this.Event.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UserTotalPoints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
