/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PointEvent
    /// </summary>
    [DataContract(Name = "PointEvent")]
    public partial class PointEvent : IEquatable<PointEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PointEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PointEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PointEvent" /> class.
        /// </summary>
        /// <param name="hash">hash (required).</param>
        /// <param name="userid">userid (required).</param>
        /// <param name="isBurn">isBurn (required).</param>
        /// <param name="points">points (required).</param>
        /// <param name="message">message (required).</param>
        /// <param name="verb">verb (required).</param>
        /// <param name="platform">platform (required).</param>
        /// <param name="icon">icon (required).</param>
        /// <param name="timestamp">timestamp (required).</param>
        /// <param name="metadata">metadata (required).</param>
        public PointEvent(string hash = default(string), string userid = default(string), bool isBurn = default(bool), decimal points = default(decimal), string message = default(string), string verb = default(string), string platform = default(string), string icon = default(string), DateTime timestamp = default(DateTime), Object metadata = default(Object))
        {
            // to ensure "hash" is required (not null)
            if (hash == null) {
                throw new ArgumentNullException("hash is a required property for PointEvent and cannot be null");
            }
            this.Hash = hash;
            // to ensure "userid" is required (not null)
            if (userid == null) {
                throw new ArgumentNullException("userid is a required property for PointEvent and cannot be null");
            }
            this.Userid = userid;
            this.IsBurn = isBurn;
            this.Points = points;
            // to ensure "message" is required (not null)
            if (message == null) {
                throw new ArgumentNullException("message is a required property for PointEvent and cannot be null");
            }
            this.Message = message;
            // to ensure "verb" is required (not null)
            if (verb == null) {
                throw new ArgumentNullException("verb is a required property for PointEvent and cannot be null");
            }
            this.Verb = verb;
            // to ensure "platform" is required (not null)
            if (platform == null) {
                throw new ArgumentNullException("platform is a required property for PointEvent and cannot be null");
            }
            this.Platform = platform;
            // to ensure "icon" is required (not null)
            if (icon == null) {
                throw new ArgumentNullException("icon is a required property for PointEvent and cannot be null");
            }
            this.Icon = icon;
            this.Timestamp = timestamp;
            // to ensure "metadata" is required (not null)
            if (metadata == null) {
                throw new ArgumentNullException("metadata is a required property for PointEvent and cannot be null");
            }
            this.Metadata = metadata;
        }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [DataMember(Name = "hash", IsRequired = true, EmitDefaultValue = false)]
        public string Hash { get; set; }

        /// <summary>
        /// Gets or Sets Userid
        /// </summary>
        [DataMember(Name = "userid", IsRequired = true, EmitDefaultValue = false)]
        public string Userid { get; set; }

        /// <summary>
        /// Gets or Sets IsBurn
        /// </summary>
        [DataMember(Name = "isBurn", IsRequired = true, EmitDefaultValue = true)]
        public bool IsBurn { get; set; }

        /// <summary>
        /// Gets or Sets Points
        /// </summary>
        [DataMember(Name = "points", IsRequired = true, EmitDefaultValue = false)]
        public decimal Points { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Verb
        /// </summary>
        [DataMember(Name = "verb", IsRequired = true, EmitDefaultValue = false)]
        public string Verb { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", IsRequired = true, EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets Icon
        /// </summary>
        [DataMember(Name = "icon", IsRequired = true, EmitDefaultValue = false)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = false)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PointEvent {\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  Userid: ").Append(Userid).Append("\n");
            sb.Append("  IsBurn: ").Append(IsBurn).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Verb: ").Append(Verb).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PointEvent);
        }

        /// <summary>
        /// Returns true if PointEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of PointEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PointEvent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Hash == input.Hash ||
                    (this.Hash != null &&
                    this.Hash.Equals(input.Hash))
                ) && 
                (
                    this.Userid == input.Userid ||
                    (this.Userid != null &&
                    this.Userid.Equals(input.Userid))
                ) && 
                (
                    this.IsBurn == input.IsBurn ||
                    this.IsBurn.Equals(input.IsBurn)
                ) && 
                (
                    this.Points == input.Points ||
                    this.Points.Equals(input.Points)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Verb == input.Verb ||
                    (this.Verb != null &&
                    this.Verb.Equals(input.Verb))
                ) && 
                (
                    this.Platform == input.Platform ||
                    (this.Platform != null &&
                    this.Platform.Equals(input.Platform))
                ) && 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Hash != null)
                {
                    hashCode = (hashCode * 59) + this.Hash.GetHashCode();
                }
                if (this.Userid != null)
                {
                    hashCode = (hashCode * 59) + this.Userid.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsBurn.GetHashCode();
                hashCode = (hashCode * 59) + this.Points.GetHashCode();
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                if (this.Verb != null)
                {
                    hashCode = (hashCode * 59) + this.Verb.GetHashCode();
                }
                if (this.Platform != null)
                {
                    hashCode = (hashCode * 59) + this.Platform.GetHashCode();
                }
                if (this.Icon != null)
                {
                    hashCode = (hashCode * 59) + this.Icon.GetHashCode();
                }
                if (this.Timestamp != null)
                {
                    hashCode = (hashCode * 59) + this.Timestamp.GetHashCode();
                }
                if (this.Metadata != null)
                {
                    hashCode = (hashCode * 59) + this.Metadata.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
