/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ClientCredentialsResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientCredentialsResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientCredentialsResponseDto
        //private ClientCredentialsResponseDto instance;

        public ClientCredentialsResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ClientCredentialsResponseDto
            //instance = new ClientCredentialsResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientCredentialsResponseDto
        /// </summary>
        [Fact]
        public void ClientCredentialsResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientCredentialsResponseDto
            //Assert.IsType<ClientCredentialsResponseDto>(instance);
        }


        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

    }

}
