/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ClientCredentialsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientCredentialsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientCredentialsDto
        //private ClientCredentialsDto instance;

        public ClientCredentialsDtoTests()
        {
            // TODO uncomment below to create an instance of ClientCredentialsDto
            //instance = new ClientCredentialsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientCredentialsDto
        /// </summary>
        [Fact]
        public void ClientCredentialsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientCredentialsDto
            //Assert.IsType<ClientCredentialsDto>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }

    }

}
