/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePlatformConnectionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePlatformConnectionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePlatformConnectionDto
        //private CreatePlatformConnectionDto instance;

        public CreatePlatformConnectionDtoTests()
        {
            // TODO uncomment below to create an instance of CreatePlatformConnectionDto
            //instance = new CreatePlatformConnectionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePlatformConnectionDto
        /// </summary>
        [Fact]
        public void CreatePlatformConnectionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePlatformConnectionDto
            //Assert.IsType<CreatePlatformConnectionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Userid'
        /// </summary>
        [Fact]
        public void UseridTest()
        {
            // TODO unit test for the property 'Userid'
        }
        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Fact]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Fact]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'AuthToken'
        /// </summary>
        [Fact]
        public void AuthTokenTest()
        {
            // TODO unit test for the property 'AuthToken'
        }
        /// <summary>
        /// Test the property 'TokenSecret'
        /// </summary>
        [Fact]
        public void TokenSecretTest()
        {
            // TODO unit test for the property 'TokenSecret'
        }
        /// <summary>
        /// Test the property 'AuthExpiration'
        /// </summary>
        [Fact]
        public void AuthExpirationTest()
        {
            // TODO unit test for the property 'AuthExpiration'
        }

    }

}
