/*
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePointEventResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePointEventResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePointEventResponseDto
        //private CreatePointEventResponseDto instance;

        public CreatePointEventResponseDtoTests()
        {
            // TODO uncomment below to create an instance of CreatePointEventResponseDto
            //instance = new CreatePointEventResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePointEventResponseDto
        /// </summary>
        [Fact]
        public void CreatePointEventResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePointEventResponseDto
            //Assert.IsType<CreatePointEventResponseDto>(instance);
        }


        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Fact]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'UserTotalPoints'
        /// </summary>
        [Fact]
        public void UserTotalPointsTest()
        {
            // TODO unit test for the property 'UserTotalPoints'
        }

    }

}
